import { Tool, User, Message, Notification, Review, BorrowRequest, UserReport } from "@/types";

export const mockUsers: User[] = [
  {
    id: "1",
    name: "John Doe",
    email: "john@example.com",
    role: "lender",
    rating: 4.8,
    totalRentals: 25,
    joinedDate: "2024-01-15",
  },
  {
    id: "2",
    name: "Jane Smith",
    email: "jane@example.com",
    role: "borrower",
    rating: 4.5,
    totalRentals: 12,
    joinedDate: "2024-02-10",
  },
  {
    id: "admin",
    name: "Admin User",
    email: "admin@lelodedo.com",
    role: "admin",
    rating: 5.0,
    totalRentals: 0,
    joinedDate: "2023-12-01",
  },
];

export const mockTools: Tool[] = [
  {
    id: "1",
    title: "Power Drill Set",
    description: "Professional 18V cordless drill with multiple bits and carrying case.",
    condition: "excellent",
    category: "Power Tools",
    image: "https://images.unsplash.com/photo-1504148455328-c376907d081c?w=800",
    images: ["https://images.unsplash.com/photo-1504148455328-c376907d081c?w=800"],
    ownerId: "1",
    ownerName: "John Doe",
    distance: 2.5,
    available: true,
    rating: 4.9,
    pricePerDay: 15,
  },
  {
    id: "2",
    title: "Ladder 12ft",
    description: "Sturdy aluminum extension ladder, perfect for home projects.",
    condition: "good",
    category: "Ladders",
    image: "https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?w=800",
    images: ["https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?w=800"],
    ownerId: "1",
    ownerName: "John Doe",
    distance: 2.5,
    available: true,
    rating: 4.7,
    pricePerDay: 10,
  },
  {
    id: "3",
    title: "Circular Saw",
    description: "Heavy-duty circular saw with laser guide for precision cuts.",
    condition: "excellent",
    category: "Power Tools",
    image: "https://images.unsplash.com/photo-1572981779307-38b8cabb2407?w=800",
    images: ["https://images.unsplash.com/photo-1572981779307-38b8cabb2407?w=800"],
    ownerId: "1",
    ownerName: "John Doe",
    distance: 3.2,
    available: false,
    rating: 5.0,
    pricePerDay: 20,
  },
  {
    id: "4",
    title: "Pressure Washer",
    description: "3000 PSI electric pressure washer for cleaning decks and driveways.",
    condition: "good",
    category: "Cleaning",
    image: "https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?w=800",
    images: ["https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?w=800"],
    ownerId: "2",
    ownerName: "Jane Smith",
    distance: 1.8,
    available: true,
    rating: 4.6,
    pricePerDay: 25,
  },
];

export const mockMessages: Message[] = [
  {
    id: "1",
    senderId: "2",
    senderName: "Jane Smith",
    receiverId: "1",
    content: "Hi! Is the power drill still available for next week?",
    timestamp: "2024-03-15T10:30:00",
    read: true,
  },
  {
    id: "2",
    senderId: "1",
    senderName: "John Doe",
    receiverId: "2",
    content: "Yes, it's available! When do you need it?",
    timestamp: "2024-03-15T11:15:00",
    read: true,
  },
  {
    id: "3",
    senderId: "2",
    senderName: "Jane Smith",
    receiverId: "1",
    content: "Perfect! I need it from Monday to Wednesday.",
    timestamp: "2024-03-15T11:20:00",
    read: false,
  },
];

export const mockNotifications: Notification[] = [
  {
    id: "1",
    type: "request",
    title: "New Rental Request",
    message: "Jane Smith wants to rent your Power Drill Set",
    timestamp: "2024-03-15T09:00:00",
    read: false,
  },
  {
    id: "2",
    type: "approval",
    title: "Request Approved",
    message: "Your rental request for Ladder 12ft has been approved",
    timestamp: "2024-03-14T15:30:00",
    read: true,
  },
  {
    id: "3",
    type: "message",
    title: "New Message",
    message: "John Doe sent you a message",
    timestamp: "2024-03-15T11:15:00",
    read: false,
  },
];

export const mockReviews: Review[] = [
  {
    id: "1",
    toolId: "1",
    userId: "2",
    userName: "Jane Smith",
    rating: 5,
    comment: "Excellent drill, worked perfectly for my project!",
    timestamp: "2024-03-10T14:20:00",
  },
  {
    id: "2",
    toolId: "2",
    userId: "2",
    userName: "Jane Smith",
    rating: 4,
    comment: "Good ladder, sturdy and reliable. Could use some cleaning.",
    timestamp: "2024-03-08T10:45:00",
  },
];

export const mockBorrowRequests: BorrowRequest[] = [
  {
    id: "1",
    toolId: "1",
    toolName: "Power Drill Set",
    borrowerId: "2",
    borrowerName: "Jane Smith",
    lenderId: "1",
    lenderName: "John Doe",
    startDate: "2024-03-20",
    endDate: "2024-03-25",
    status: "pending",
    timestamp: "2024-03-15T10:30:00",
  },
  {
    id: "2",
    toolId: "2",
    toolName: "Ladder 12ft",
    borrowerId: "2",
    borrowerName: "Jane Smith",
    lenderId: "1",
    lenderName: "John Doe",
    startDate: "2024-03-22",
    endDate: "2024-03-24",
    status: "accepted",
    timestamp: "2024-03-14T15:00:00",
  },
];

export const mockUserReports: UserReport[] = [
  {
    id: "1",
    reporterId: "2",
    reporterName: "Jane Smith",
    reportedUserId: "1",
    reportedUserName: "John Doe",
    reason: "Tool not as described",
    description: "The tool was in much worse condition than advertised.",
    timestamp: "2024-03-10T16:00:00",
    status: "pending",
  },
];
